# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: app/protos/audio.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'app/protos/audio.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16\x61pp/protos/audio.proto\"4\n\x0c\x41udioRequest\x12\x12\n\naudio_data\x18\x01 \x01(\x0c\x12\x10\n\x08is_final\x18\x02 \x01(\x08\"\x1d\n\rAudioResponse\x12\x0c\n\x04text\x18\x01 \x01(\t2C\n\rSpeechService\x12\x32\n\x0fSendAudioStream\x12\r.AudioRequest\x1a\x0e.AudioResponse(\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'app.protos.audio_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_AUDIOREQUEST']._serialized_start=26
  _globals['_AUDIOREQUEST']._serialized_end=78
  _globals['_AUDIORESPONSE']._serialized_start=80
  _globals['_AUDIORESPONSE']._serialized_end=109
  _globals['_SPEECHSERVICE']._serialized_start=111
  _globals['_SPEECHSERVICE']._serialized_end=178
# @@protoc_insertion_point(module_scope)
